// Mocks generated by Mockito 5.1.0 from annotations
// in internship_app_fis/test/internship_service_unit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:internship_app_fis/dao/base_dao.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mysql1/mysql1.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMySqlConnection_0 extends _i1.Fake implements _i2.MySqlConnection {}

class _FakeResults_1 extends _i1.Fake implements _i2.Results {}

class _FakeIterator_2<E> extends _i1.Fake implements Iterator<E> {}

class _FakeResultRow_3 extends _i1.Fake implements _i2.ResultRow {}

/// A class which mocks [BaseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseDao extends _i1.Mock implements _i3.BaseDao {
  MockBaseDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MySqlConnection> get initDb =>
      (super.noSuchMethod(Invocation.getter(#initDb),
              returnValue:
                  Future<_i2.MySqlConnection>.value(_FakeMySqlConnection_0()))
          as _i4.Future<_i2.MySqlConnection>);
}

/// A class which mocks [Future].
///
/// See the documentation for Mockito's code generation for more information.
class MockFuture<T> extends _i1.Mock implements _i4.Future<T> {
  MockFuture() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<R> then<R>(_i4.FutureOr<R>? Function(T)? onValue,
          {Function? onError}) =>
      (super.noSuchMethod(
          Invocation.method(#then, [onValue], {#onError: onError}),
          returnValue: Future<R>.value(null)) as _i4.Future<R>);
  @override
  _i4.Future<T> catchError(Function? onError, {bool Function(Object)? test}) =>
      (super.noSuchMethod(
          Invocation.method(#catchError, [onError], {#test: test}),
          returnValue: Future<T>.value(null)) as _i4.Future<T>);
  @override
  _i4.Future<T> whenComplete(_i4.FutureOr<void>? Function()? action) =>
      (super.noSuchMethod(Invocation.method(#whenComplete, [action]),
          returnValue: Future<T>.value(null)) as _i4.Future<T>);
  @override
  _i4.Stream<T> asStream() =>
      (super.noSuchMethod(Invocation.method(#asStream, []),
          returnValue: Stream<T>.empty()) as _i4.Stream<T>);
  @override
  _i4.Future<T> timeout(Duration? timeLimit,
          {_i4.FutureOr<T>? Function()? onTimeout}) =>
      (super.noSuchMethod(
          Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
          returnValue: Future<T>.value(null)) as _i4.Future<T>);
}

/// A class which mocks [MySqlConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockMySqlConnection extends _i1.Mock implements _i2.MySqlConnection {
  MockMySqlConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<dynamic> close() =>
      (super.noSuchMethod(Invocation.method(#close, []),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  _i4.Future<_i2.Results> query(String? sql, [List<Object?>? values]) =>
      (super.noSuchMethod(Invocation.method(#query, [sql, values]),
              returnValue: Future<_i2.Results>.value(_FakeResults_1()))
          as _i4.Future<_i2.Results>);
  @override
  _i4.Future<List<_i2.Results>> queryMulti(
          String? sql, Iterable<List<Object?>>? values) =>
      (super.noSuchMethod(Invocation.method(#queryMulti, [sql, values]),
              returnValue: Future<List<_i2.Results>>.value(<_i2.Results>[]))
          as _i4.Future<List<_i2.Results>>);
  @override
  _i4.Future<dynamic> transaction(Function? queryBlock) =>
      (super.noSuchMethod(Invocation.method(#transaction, [queryBlock]),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
}

/// A class which mocks [Results].
///
/// See the documentation for Mockito's code generation for more information.
class MockResults extends _i1.Mock implements _i2.Results {
  MockResults() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Field> get fields => (super.noSuchMethod(Invocation.getter(#fields),
      returnValue: <_i2.Field>[]) as List<_i2.Field>);
  @override
  Iterator<_i2.ResultRow> get iterator =>
      (super.noSuchMethod(Invocation.getter(#iterator),
              returnValue: _FakeIterator_2<_i2.ResultRow>())
          as Iterator<_i2.ResultRow>);
  @override
  int get length =>
      (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);
  @override
  bool get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false)
          as bool);
  @override
  bool get isNotEmpty =>
      (super.noSuchMethod(Invocation.getter(#isNotEmpty), returnValue: false)
          as bool);
  @override
  _i2.ResultRow get first => (super.noSuchMethod(Invocation.getter(#first),
      returnValue: _FakeResultRow_3()) as _i2.ResultRow);
  @override
  _i2.ResultRow get last => (super.noSuchMethod(Invocation.getter(#last),
      returnValue: _FakeResultRow_3()) as _i2.ResultRow);
  @override
  _i2.ResultRow get single => (super.noSuchMethod(Invocation.getter(#single),
      returnValue: _FakeResultRow_3()) as _i2.ResultRow);
  @override
  Iterable<R> cast<R>() =>
      (super.noSuchMethod(Invocation.method(#cast, []), returnValue: <R>[])
          as Iterable<R>);
  @override
  Iterable<_i2.ResultRow> followedBy(Iterable<_i2.ResultRow>? other) =>
      (super.noSuchMethod(Invocation.method(#followedBy, [other]),
          returnValue: <_i2.ResultRow>[]) as Iterable<_i2.ResultRow>);
  @override
  Iterable<T> map<T>(T Function(_i2.ResultRow)? toElement) =>
      (super.noSuchMethod(Invocation.method(#map, [toElement]),
          returnValue: <T>[]) as Iterable<T>);
  @override
  Iterable<_i2.ResultRow> where(bool Function(_i2.ResultRow)? test) =>
      (super.noSuchMethod(Invocation.method(#where, [test]),
          returnValue: <_i2.ResultRow>[]) as Iterable<_i2.ResultRow>);
  @override
  Iterable<T> whereType<T>() =>
      (super.noSuchMethod(Invocation.method(#whereType, []), returnValue: <T>[])
          as Iterable<T>);
  @override
  Iterable<T> expand<T>(Iterable<T> Function(_i2.ResultRow)? toElements) =>
      (super.noSuchMethod(Invocation.method(#expand, [toElements]),
          returnValue: <T>[]) as Iterable<T>);
  @override
  bool contains(Object? element) =>
      (super.noSuchMethod(Invocation.method(#contains, [element]),
          returnValue: false) as bool);
  @override
  void forEach(void Function(_i2.ResultRow)? action) =>
      super.noSuchMethod(Invocation.method(#forEach, [action]),
          returnValueForMissingStub: null);
  @override
  _i2.ResultRow reduce(
          _i2.ResultRow Function(_i2.ResultRow, _i2.ResultRow)? combine) =>
      (super.noSuchMethod(Invocation.method(#reduce, [combine]),
          returnValue: _FakeResultRow_3()) as _i2.ResultRow);
  @override
  T fold<T>(T? initialValue, T Function(T, _i2.ResultRow)? combine) =>
      throw UnsupportedError(
          '\'fold\' cannot be used without a mockito fallback generator.');
  @override
  bool every(bool Function(_i2.ResultRow)? test) =>
      (super.noSuchMethod(Invocation.method(#every, [test]), returnValue: false)
          as bool);
  @override
  String join([String? separator = r'']) => (super
          .noSuchMethod(Invocation.method(#join, [separator]), returnValue: '')
      as String);
  @override
  bool any(bool Function(_i2.ResultRow)? test) =>
      (super.noSuchMethod(Invocation.method(#any, [test]), returnValue: false)
          as bool);
  @override
  List<_i2.ResultRow> toList({bool? growable = true}) =>
      (super.noSuchMethod(Invocation.method(#toList, [], {#growable: growable}),
          returnValue: <_i2.ResultRow>[]) as List<_i2.ResultRow>);
  @override
  Set<_i2.ResultRow> toSet() =>
      (super.noSuchMethod(Invocation.method(#toSet, []),
          returnValue: <_i2.ResultRow>{}) as Set<_i2.ResultRow>);
  @override
  Iterable<_i2.ResultRow> take(int? count) =>
      (super.noSuchMethod(Invocation.method(#take, [count]),
          returnValue: <_i2.ResultRow>[]) as Iterable<_i2.ResultRow>);
  @override
  Iterable<_i2.ResultRow> takeWhile(bool Function(_i2.ResultRow)? test) =>
      (super.noSuchMethod(Invocation.method(#takeWhile, [test]),
          returnValue: <_i2.ResultRow>[]) as Iterable<_i2.ResultRow>);
  @override
  Iterable<_i2.ResultRow> skip(int? count) =>
      (super.noSuchMethod(Invocation.method(#skip, [count]),
          returnValue: <_i2.ResultRow>[]) as Iterable<_i2.ResultRow>);
  @override
  Iterable<_i2.ResultRow> skipWhile(bool Function(_i2.ResultRow)? test) =>
      (super.noSuchMethod(Invocation.method(#skipWhile, [test]),
          returnValue: <_i2.ResultRow>[]) as Iterable<_i2.ResultRow>);
  @override
  _i2.ResultRow firstWhere(bool Function(_i2.ResultRow)? test,
          {_i2.ResultRow Function()? orElse}) =>
      (super.noSuchMethod(
          Invocation.method(#firstWhere, [test], {#orElse: orElse}),
          returnValue: _FakeResultRow_3()) as _i2.ResultRow);
  @override
  _i2.ResultRow lastWhere(bool Function(_i2.ResultRow)? test,
          {_i2.ResultRow Function()? orElse}) =>
      (super.noSuchMethod(
          Invocation.method(#lastWhere, [test], {#orElse: orElse}),
          returnValue: _FakeResultRow_3()) as _i2.ResultRow);
  @override
  _i2.ResultRow singleWhere(bool Function(_i2.ResultRow)? test,
          {_i2.ResultRow Function()? orElse}) =>
      (super.noSuchMethod(
          Invocation.method(#singleWhere, [test], {#orElse: orElse}),
          returnValue: _FakeResultRow_3()) as _i2.ResultRow);
  @override
  _i2.ResultRow elementAt(int? index) =>
      (super.noSuchMethod(Invocation.method(#elementAt, [index]),
          returnValue: _FakeResultRow_3()) as _i2.ResultRow);
}
