// Mocks generated by Mockito 5.2.0 from annotations
// in internship_app_fis/test/internships_main_page_widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:typed_data' as _i8;

import 'package:file/file.dart' as _i4;
import 'package:flutter/widgets.dart' as _i16;
import 'package:flutter_cache_manager/flutter_cache_manager.dart' as _i5;
import 'package:flutter_cache_manager/src/cache_store.dart' as _i2;
import 'package:flutter_cache_manager/src/web/web_helper.dart' as _i3;
import 'package:internship_app_fis/models/internship.dart' as _i12;
import 'package:internship_app_fis/models/user.dart' as _i10;
import 'package:internship_app_fis/models/user_profile.dart' as _i15;
import 'package:internship_app_fis/services/auth_service.dart' as _i13;
import 'package:internship_app_fis/services/internship_service.dart' as _i11;
import 'package:internship_app_fis/services/user_profile_service.dart' as _i14;
import 'package:internship_app_fis/services/user_service.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mysql1/mysql1.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCacheStore_0 extends _i1.Fake implements _i2.CacheStore {}

class _FakeWebHelper_1 extends _i1.Fake implements _i3.WebHelper {}

class _FakeFile_2 extends _i1.Fake implements _i4.File {}

class _FakeFileInfo_3 extends _i1.Fake implements _i5.FileInfo {}

class _FakeStreamSubscription_4<T> extends _i1.Fake
    implements _i6.StreamSubscription<T> {}

class _FakeIterator_5<E> extends _i1.Fake implements Iterator<E> {}

class _FakeResultRow_6 extends _i1.Fake implements _i7.ResultRow {}

/// A class which mocks [DefaultCacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDefaultCacheManager extends _i1.Mock
    implements _i5.DefaultCacheManager {
  MockDefaultCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CacheStore get store => (super.noSuchMethod(Invocation.getter(#store),
      returnValue: _FakeCacheStore_0()) as _i2.CacheStore);
  @override
  _i3.WebHelper get webHelper =>
      (super.noSuchMethod(Invocation.getter(#webHelper),
          returnValue: _FakeWebHelper_1()) as _i3.WebHelper);
  @override
  _i6.Future<_i4.File> getSingleFile(String? url,
          {String? key, Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getSingleFile, [url], {#key: key, #headers: headers}),
              returnValue: Future<_i4.File>.value(_FakeFile_2()))
          as _i6.Future<_i4.File>);
  @override
  _i6.Stream<_i5.FileInfo> getFile(String? url,
          {String? key, Map<String, String>? headers}) =>
      (super.noSuchMethod(
          Invocation.method(#getFile, [url], {#key: key, #headers: headers}),
          returnValue:
              Stream<_i5.FileInfo>.empty()) as _i6.Stream<_i5.FileInfo>);
  @override
  _i6.Stream<_i5.FileResponse> getFileStream(String? url,
          {String? key,
          Map<String, String>? headers,
          bool? withProgress = false}) =>
      (super.noSuchMethod(
              Invocation.method(#getFileStream, [url],
                  {#key: key, #headers: headers, #withProgress: withProgress}),
              returnValue: Stream<_i5.FileResponse>.empty())
          as _i6.Stream<_i5.FileResponse>);
  @override
  _i6.Future<_i5.FileInfo> downloadFile(String? url,
          {String? key,
          Map<String, String>? authHeaders,
          bool? force = false}) =>
      (super.noSuchMethod(
              Invocation.method(#downloadFile, [url],
                  {#key: key, #authHeaders: authHeaders, #force: force}),
              returnValue: Future<_i5.FileInfo>.value(_FakeFileInfo_3()))
          as _i6.Future<_i5.FileInfo>);
  @override
  _i6.Future<_i5.FileInfo?> getFileFromCache(String? key,
          {bool? ignoreMemCache = false}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getFileFromCache, [key], {#ignoreMemCache: ignoreMemCache}),
              returnValue: Future<_i5.FileInfo?>.value())
          as _i6.Future<_i5.FileInfo?>);
  @override
  _i6.Future<_i5.FileInfo?> getFileFromMemory(String? key) =>
      (super.noSuchMethod(Invocation.method(#getFileFromMemory, [key]),
              returnValue: Future<_i5.FileInfo?>.value())
          as _i6.Future<_i5.FileInfo?>);
  @override
  _i6.Future<_i4.File> putFile(String? url, _i8.Uint8List? fileBytes,
          {String? key,
          String? eTag,
          Duration? maxAge = const Duration(days: 30),
          String? fileExtension = r'file'}) =>
      (super.noSuchMethod(
              Invocation.method(#putFile, [
                url,
                fileBytes
              ], {
                #key: key,
                #eTag: eTag,
                #maxAge: maxAge,
                #fileExtension: fileExtension
              }),
              returnValue: Future<_i4.File>.value(_FakeFile_2()))
          as _i6.Future<_i4.File>);
  @override
  _i6.Future<_i4.File> putFileStream(String? url, _i6.Stream<List<int>>? source,
          {String? key,
          String? eTag,
          Duration? maxAge = const Duration(days: 30),
          String? fileExtension = r'file'}) =>
      (super.noSuchMethod(
              Invocation.method(#putFileStream, [
                url,
                source
              ], {
                #key: key,
                #eTag: eTag,
                #maxAge: maxAge,
                #fileExtension: fileExtension
              }),
              returnValue: Future<_i4.File>.value(_FakeFile_2()))
          as _i6.Future<_i4.File>);
  @override
  _i6.Future<void> removeFile(String? key) =>
      (super.noSuchMethod(Invocation.method(#removeFile, [key]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> emptyCache() =>
      (super.noSuchMethod(Invocation.method(#emptyCache, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Stream<_i5.FileResponse> getImageFile(String? url,
          {String? key,
          Map<String, String>? headers,
          bool? withProgress = false,
          int? maxHeight,
          int? maxWidth}) =>
      (super.noSuchMethod(
              Invocation.method(#getImageFile, [
                url
              ], {
                #key: key,
                #headers: headers,
                #withProgress: withProgress,
                #maxHeight: maxHeight,
                #maxWidth: maxWidth
              }),
              returnValue: Stream<_i5.FileResponse>.empty())
          as _i6.Stream<_i5.FileResponse>);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i9.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i10.User?> getUser(_i10.User? user) =>
      (super.noSuchMethod(Invocation.method(#getUser, [user]),
          returnValue: Future<_i10.User?>.value()) as _i6.Future<_i10.User?>);
  @override
  _i6.Future<bool> usernameExists(_i10.User? user) =>
      (super.noSuchMethod(Invocation.method(#usernameExists, [user]),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<void> addUser(_i10.User? user) =>
      (super.noSuchMethod(Invocation.method(#addUser, [user]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> deleteUser(_i10.User? user) =>
      (super.noSuchMethod(Invocation.method(#deleteUser, [user]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
}

/// A class which mocks [InternshipService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternshipService extends _i1.Mock implements _i11.InternshipService {
  MockInternshipService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> addInternship(_i12.Internship? internship) =>
      (super.noSuchMethod(Invocation.method(#addInternship, [internship]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<List<_i12.Internship>> getAllCompanyInternships(
          _i10.Company? company) =>
      (super.noSuchMethod(
              Invocation.method(#getAllCompanyInternships, [company]),
              returnValue:
                  Future<List<_i12.Internship>>.value(<_i12.Internship>[]))
          as _i6.Future<List<_i12.Internship>>);
  @override
  _i6.Future<List<_i12.Internship>> getAllInternships() => (super.noSuchMethod(
          Invocation.method(#getAllInternships, []),
          returnValue: Future<List<_i12.Internship>>.value(<_i12.Internship>[]))
      as _i6.Future<List<_i12.Internship>>);
  @override
  _i6.Future<List<_i12.Internship>> getStudentNotAppliedInternship(
          _i10.Student? user) =>
      (super.noSuchMethod(
              Invocation.method(#getStudentNotAppliedInternship, [user]),
              returnValue:
                  Future<List<_i12.Internship>>.value(<_i12.Internship>[]))
          as _i6.Future<List<_i12.Internship>>);
  @override
  _i6.Future<void> deleteInternship(_i12.Internship? internship) =>
      (super.noSuchMethod(Invocation.method(#deleteInternship, [internship]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> updateInternship(_i12.Internship? internship) =>
      (super.noSuchMethod(Invocation.method(#updateInternship, [internship]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i13.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i10.User?> signupUser() =>
      (super.noSuchMethod(Invocation.method(#signupUser, []),
          returnValue: Future<_i10.User?>.value()) as _i6.Future<_i10.User?>);
  @override
  _i6.Future<_i10.User?> loginUser() =>
      (super.noSuchMethod(Invocation.method(#loginUser, []),
          returnValue: Future<_i10.User?>.value()) as _i6.Future<_i10.User?>);
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i14.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i15.UserProfile?> getUserProfileById(_i10.User? user) =>
      (super.noSuchMethod(Invocation.method(#getUserProfileById, [user]),
              returnValue: Future<_i15.UserProfile?>.value())
          as _i6.Future<_i15.UserProfile?>);
  @override
  _i6.Future<void> addUserProfile(_i15.UserProfile? profile) =>
      (super.noSuchMethod(Invocation.method(#addUserProfile, [profile]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<List<_i15.CompanyProfile>> getAllCompanyProfiles() =>
      (super.noSuchMethod(Invocation.method(#getAllCompanyProfiles, []),
              returnValue: Future<List<_i15.CompanyProfile>>.value(
                  <_i15.CompanyProfile>[]))
          as _i6.Future<List<_i15.CompanyProfile>>);
  @override
  _i6.Future<List<_i15.StudentProfile>> getAcceptedParticipantsList(
          _i12.Internship? internship) =>
      (super.noSuchMethod(
              Invocation.method(#getAcceptedParticipantsList, [internship]),
              returnValue: Future<List<_i15.StudentProfile>>.value(
                  <_i15.StudentProfile>[]))
          as _i6.Future<List<_i15.StudentProfile>>);
  @override
  _i6.Future<List<_i15.StudentProfile>> getStudentProfilesByInternshipId(
          _i12.Internship? internship) =>
      (super.noSuchMethod(
          Invocation.method(#getStudentProfilesByInternshipId, [internship]),
          returnValue: Future<List<_i15.StudentProfile>>.value(
              <_i15.StudentProfile>[])) as _i6
          .Future<List<_i15.StudentProfile>>);
  @override
  _i6.Future<void> addAcceptedParticipantsList(
          _i12.Internship? internship, List<_i15.UserProfile>? userProfiles) =>
      (super.noSuchMethod(
          Invocation.method(
              #addAcceptedParticipantsList, [internship, userProfiles]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
}

/// A class which mocks [Stream].
///
/// See the documentation for Mockito's code generation for more information.
class MockStream<T> extends _i1.Mock implements _i6.Stream<T> {
  MockStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isBroadcast =>
      (super.noSuchMethod(Invocation.getter(#isBroadcast), returnValue: false)
          as bool);
  @override
  _i6.Future<int> get length => (super.noSuchMethod(Invocation.getter(#length),
      returnValue: Future<int>.value(0)) as _i6.Future<int>);
  @override
  _i6.Future<bool> get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<T> get first => (super.noSuchMethod(Invocation.getter(#first),
      returnValue: Future<T>.value(null)) as _i6.Future<T>);
  @override
  _i6.Future<T> get last => (super.noSuchMethod(Invocation.getter(#last),
      returnValue: Future<T>.value(null)) as _i6.Future<T>);
  @override
  _i6.Future<T> get single => (super.noSuchMethod(Invocation.getter(#single),
      returnValue: Future<T>.value(null)) as _i6.Future<T>);
  @override
  _i6.Stream<T> asBroadcastStream(
          {void Function(_i6.StreamSubscription<T>)? onListen,
          void Function(_i6.StreamSubscription<T>)? onCancel}) =>
      (super.noSuchMethod(
          Invocation.method(#asBroadcastStream, [],
              {#onListen: onListen, #onCancel: onCancel}),
          returnValue: Stream<T>.empty()) as _i6.Stream<T>);
  @override
  _i6.StreamSubscription<T> listen(void Function(T)? onData,
          {Function? onError, void Function()? onDone, bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_4<T>())
          as _i6.StreamSubscription<T>);
  @override
  _i6.Stream<T> where(bool Function(T)? test) =>
      (super.noSuchMethod(Invocation.method(#where, [test]),
          returnValue: Stream<T>.empty()) as _i6.Stream<T>);
  @override
  _i6.Stream<S> map<S>(S Function(T)? convert) =>
      (super.noSuchMethod(Invocation.method(#map, [convert]),
          returnValue: Stream<S>.empty()) as _i6.Stream<S>);
  @override
  _i6.Stream<E> asyncMap<E>(_i6.FutureOr<E> Function(T)? convert) =>
      (super.noSuchMethod(Invocation.method(#asyncMap, [convert]),
          returnValue: Stream<E>.empty()) as _i6.Stream<E>);
  @override
  _i6.Stream<E> asyncExpand<E>(_i6.Stream<E>? Function(T)? convert) =>
      (super.noSuchMethod(Invocation.method(#asyncExpand, [convert]),
          returnValue: Stream<E>.empty()) as _i6.Stream<E>);
  @override
  _i6.Stream<T> handleError(Function? onError,
          {bool Function(dynamic)? test}) =>
      (super.noSuchMethod(
          Invocation.method(#handleError, [onError], {#test: test}),
          returnValue: Stream<T>.empty()) as _i6.Stream<T>);
  @override
  _i6.Stream<S> expand<S>(Iterable<S> Function(T)? convert) =>
      (super.noSuchMethod(Invocation.method(#expand, [convert]),
          returnValue: Stream<S>.empty()) as _i6.Stream<S>);
  @override
  _i6.Future<dynamic> pipe(_i6.StreamConsumer<T>? streamConsumer) =>
      (super.noSuchMethod(Invocation.method(#pipe, [streamConsumer]),
          returnValue: Future<dynamic>.value()) as _i6.Future<dynamic>);
  @override
  _i6.Stream<S> transform<S>(_i6.StreamTransformer<T, S>? streamTransformer) =>
      (super.noSuchMethod(Invocation.method(#transform, [streamTransformer]),
          returnValue: Stream<S>.empty()) as _i6.Stream<S>);
  @override
  _i6.Future<T> reduce(T Function(T, T)? combine) =>
      (super.noSuchMethod(Invocation.method(#reduce, [combine]),
          returnValue: Future<T>.value(null)) as _i6.Future<T>);
  @override
  _i6.Future<S> fold<S>(S? initialValue, S Function(S, T)? combine) =>
      (super.noSuchMethod(Invocation.method(#fold, [initialValue, combine]),
          returnValue: Future<S>.value(null)) as _i6.Future<S>);
  @override
  _i6.Future<String> join([String? separator = r'']) =>
      (super.noSuchMethod(Invocation.method(#join, [separator]),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<bool> contains(Object? needle) =>
      (super.noSuchMethod(Invocation.method(#contains, [needle]),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<dynamic> forEach(void Function(T)? action) =>
      (super.noSuchMethod(Invocation.method(#forEach, [action]),
          returnValue: Future<dynamic>.value()) as _i6.Future<dynamic>);
  @override
  _i6.Future<bool> every(bool Function(T)? test) =>
      (super.noSuchMethod(Invocation.method(#every, [test]),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<bool> any(bool Function(T)? test) =>
      (super.noSuchMethod(Invocation.method(#any, [test]),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Stream<R> cast<R>() => (super.noSuchMethod(Invocation.method(#cast, []),
      returnValue: Stream<R>.empty()) as _i6.Stream<R>);
  @override
  _i6.Future<List<T>> toList() =>
      (super.noSuchMethod(Invocation.method(#toList, []),
          returnValue: Future<List<T>>.value(<T>[])) as _i6.Future<List<T>>);
  @override
  _i6.Future<Set<T>> toSet() =>
      (super.noSuchMethod(Invocation.method(#toSet, []),
          returnValue: Future<Set<T>>.value(<T>{})) as _i6.Future<Set<T>>);
  @override
  _i6.Future<E> drain<E>([E? futureValue]) =>
      (super.noSuchMethod(Invocation.method(#drain, [futureValue]),
          returnValue: Future<E>.value(null)) as _i6.Future<E>);
  @override
  _i6.Stream<T> take(int? count) =>
      (super.noSuchMethod(Invocation.method(#take, [count]),
          returnValue: Stream<T>.empty()) as _i6.Stream<T>);
  @override
  _i6.Stream<T> takeWhile(bool Function(T)? test) =>
      (super.noSuchMethod(Invocation.method(#takeWhile, [test]),
          returnValue: Stream<T>.empty()) as _i6.Stream<T>);
  @override
  _i6.Stream<T> skip(int? count) =>
      (super.noSuchMethod(Invocation.method(#skip, [count]),
          returnValue: Stream<T>.empty()) as _i6.Stream<T>);
  @override
  _i6.Stream<T> skipWhile(bool Function(T)? test) =>
      (super.noSuchMethod(Invocation.method(#skipWhile, [test]),
          returnValue: Stream<T>.empty()) as _i6.Stream<T>);
  @override
  _i6.Stream<T> distinct([bool Function(T, T)? equals]) =>
      (super.noSuchMethod(Invocation.method(#distinct, [equals]),
          returnValue: Stream<T>.empty()) as _i6.Stream<T>);
  @override
  _i6.Future<T> firstWhere(bool Function(T)? test, {T Function()? orElse}) =>
      (super.noSuchMethod(
          Invocation.method(#firstWhere, [test], {#orElse: orElse}),
          returnValue: Future<T>.value(null)) as _i6.Future<T>);
  @override
  _i6.Future<T> lastWhere(bool Function(T)? test, {T Function()? orElse}) =>
      (super.noSuchMethod(
          Invocation.method(#lastWhere, [test], {#orElse: orElse}),
          returnValue: Future<T>.value(null)) as _i6.Future<T>);
  @override
  _i6.Future<T> singleWhere(bool Function(T)? test, {T Function()? orElse}) =>
      (super.noSuchMethod(
          Invocation.method(#singleWhere, [test], {#orElse: orElse}),
          returnValue: Future<T>.value(null)) as _i6.Future<T>);
  @override
  _i6.Future<T> elementAt(int? index) =>
      (super.noSuchMethod(Invocation.method(#elementAt, [index]),
          returnValue: Future<T>.value(null)) as _i6.Future<T>);
  @override
  _i6.Stream<T> timeout(Duration? timeLimit,
          {void Function(_i6.EventSink<T>)? onTimeout}) =>
      (super.noSuchMethod(
          Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
          returnValue: Stream<T>.empty()) as _i6.Stream<T>);
}

/// A class which mocks [StreamSubscription].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamSubscription<T> extends _i1.Mock
    implements _i6.StreamSubscription<T> {
  MockStreamSubscription() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isPaused =>
      (super.noSuchMethod(Invocation.getter(#isPaused), returnValue: false)
          as bool);
  @override
  _i6.Future<void> cancel() =>
      (super.noSuchMethod(Invocation.method(#cancel, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void onData(void Function(T)? handleData) =>
      super.noSuchMethod(Invocation.method(#onData, [handleData]),
          returnValueForMissingStub: null);
  @override
  void onError(Function? handleError) =>
      super.noSuchMethod(Invocation.method(#onError, [handleError]),
          returnValueForMissingStub: null);
  @override
  void onDone(void Function()? handleDone) =>
      super.noSuchMethod(Invocation.method(#onDone, [handleDone]),
          returnValueForMissingStub: null);
  @override
  void pause([_i6.Future<void>? resumeSignal]) =>
      super.noSuchMethod(Invocation.method(#pause, [resumeSignal]),
          returnValueForMissingStub: null);
  @override
  void resume() => super.noSuchMethod(Invocation.method(#resume, []),
      returnValueForMissingStub: null);
  @override
  _i6.Future<E> asFuture<E>([E? futureValue]) =>
      (super.noSuchMethod(Invocation.method(#asFuture, [futureValue]),
          returnValue: Future<E>.value(null)) as _i6.Future<E>);
}

/// A class which mocks [Results].
///
/// See the documentation for Mockito's code generation for more information.
class MockResults extends _i1.Mock implements _i7.Results {
  MockResults() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.Field> get fields => (super.noSuchMethod(Invocation.getter(#fields),
      returnValue: <_i7.Field>[]) as List<_i7.Field>);
  @override
  Iterator<_i7.ResultRow> get iterator =>
      (super.noSuchMethod(Invocation.getter(#iterator),
              returnValue: _FakeIterator_5<_i7.ResultRow>())
          as Iterator<_i7.ResultRow>);
  @override
  int get length =>
      (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);
  @override
  bool get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false)
          as bool);
  @override
  bool get isNotEmpty =>
      (super.noSuchMethod(Invocation.getter(#isNotEmpty), returnValue: false)
          as bool);
  @override
  _i7.ResultRow get first => (super.noSuchMethod(Invocation.getter(#first),
      returnValue: _FakeResultRow_6()) as _i7.ResultRow);
  @override
  _i7.ResultRow get last => (super.noSuchMethod(Invocation.getter(#last),
      returnValue: _FakeResultRow_6()) as _i7.ResultRow);
  @override
  _i7.ResultRow get single => (super.noSuchMethod(Invocation.getter(#single),
      returnValue: _FakeResultRow_6()) as _i7.ResultRow);
  @override
  Iterable<R> cast<R>() =>
      (super.noSuchMethod(Invocation.method(#cast, []), returnValue: <R>[])
          as Iterable<R>);
  @override
  Iterable<_i7.ResultRow> followedBy(Iterable<_i7.ResultRow>? other) =>
      (super.noSuchMethod(Invocation.method(#followedBy, [other]),
          returnValue: <_i7.ResultRow>[]) as Iterable<_i7.ResultRow>);
  @override
  Iterable<T> map<T>(T Function(_i7.ResultRow)? toElement) =>
      (super.noSuchMethod(Invocation.method(#map, [toElement]),
          returnValue: <T>[]) as Iterable<T>);
  @override
  Iterable<_i7.ResultRow> where(bool Function(_i7.ResultRow)? test) =>
      (super.noSuchMethod(Invocation.method(#where, [test]),
          returnValue: <_i7.ResultRow>[]) as Iterable<_i7.ResultRow>);
  @override
  Iterable<T> whereType<T>() =>
      (super.noSuchMethod(Invocation.method(#whereType, []), returnValue: <T>[])
          as Iterable<T>);
  @override
  Iterable<T> expand<T>(Iterable<T> Function(_i7.ResultRow)? toElements) =>
      (super.noSuchMethod(Invocation.method(#expand, [toElements]),
          returnValue: <T>[]) as Iterable<T>);
  @override
  bool contains(Object? element) =>
      (super.noSuchMethod(Invocation.method(#contains, [element]),
          returnValue: false) as bool);
  @override
  void forEach(void Function(_i7.ResultRow)? action) =>
      super.noSuchMethod(Invocation.method(#forEach, [action]),
          returnValueForMissingStub: null);
  @override
  _i7.ResultRow reduce(
          _i7.ResultRow Function(_i7.ResultRow, _i7.ResultRow)? combine) =>
      (super.noSuchMethod(Invocation.method(#reduce, [combine]),
          returnValue: _FakeResultRow_6()) as _i7.ResultRow);
  @override
  T fold<T>(T? initialValue, T Function(T, _i7.ResultRow)? combine) =>
      throw UnsupportedError(
          '\'fold\' cannot be used without a mockito fallback generator.');
  @override
  bool every(bool Function(_i7.ResultRow)? test) =>
      (super.noSuchMethod(Invocation.method(#every, [test]), returnValue: false)
          as bool);
  @override
  String join([String? separator = r'']) => (super
          .noSuchMethod(Invocation.method(#join, [separator]), returnValue: '')
      as String);
  @override
  bool any(bool Function(_i7.ResultRow)? test) =>
      (super.noSuchMethod(Invocation.method(#any, [test]), returnValue: false)
          as bool);
  @override
  List<_i7.ResultRow> toList({bool? growable = true}) =>
      (super.noSuchMethod(Invocation.method(#toList, [], {#growable: growable}),
          returnValue: <_i7.ResultRow>[]) as List<_i7.ResultRow>);
  @override
  Set<_i7.ResultRow> toSet() =>
      (super.noSuchMethod(Invocation.method(#toSet, []),
          returnValue: <_i7.ResultRow>{}) as Set<_i7.ResultRow>);
  @override
  Iterable<_i7.ResultRow> take(int? count) =>
      (super.noSuchMethod(Invocation.method(#take, [count]),
          returnValue: <_i7.ResultRow>[]) as Iterable<_i7.ResultRow>);
  @override
  Iterable<_i7.ResultRow> takeWhile(bool Function(_i7.ResultRow)? test) =>
      (super.noSuchMethod(Invocation.method(#takeWhile, [test]),
          returnValue: <_i7.ResultRow>[]) as Iterable<_i7.ResultRow>);
  @override
  Iterable<_i7.ResultRow> skip(int? count) =>
      (super.noSuchMethod(Invocation.method(#skip, [count]),
          returnValue: <_i7.ResultRow>[]) as Iterable<_i7.ResultRow>);
  @override
  Iterable<_i7.ResultRow> skipWhile(bool Function(_i7.ResultRow)? test) =>
      (super.noSuchMethod(Invocation.method(#skipWhile, [test]),
          returnValue: <_i7.ResultRow>[]) as Iterable<_i7.ResultRow>);
  @override
  _i7.ResultRow firstWhere(bool Function(_i7.ResultRow)? test,
          {_i7.ResultRow Function()? orElse}) =>
      (super.noSuchMethod(
          Invocation.method(#firstWhere, [test], {#orElse: orElse}),
          returnValue: _FakeResultRow_6()) as _i7.ResultRow);
  @override
  _i7.ResultRow lastWhere(bool Function(_i7.ResultRow)? test,
          {_i7.ResultRow Function()? orElse}) =>
      (super.noSuchMethod(
          Invocation.method(#lastWhere, [test], {#orElse: orElse}),
          returnValue: _FakeResultRow_6()) as _i7.ResultRow);
  @override
  _i7.ResultRow singleWhere(bool Function(_i7.ResultRow)? test,
          {_i7.ResultRow Function()? orElse}) =>
      (super.noSuchMethod(
          Invocation.method(#singleWhere, [test], {#orElse: orElse}),
          returnValue: _FakeResultRow_6()) as _i7.ResultRow);
  @override
  _i7.ResultRow elementAt(int? index) =>
      (super.noSuchMethod(Invocation.method(#elementAt, [index]),
          returnValue: _FakeResultRow_6()) as _i7.ResultRow);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i16.NavigatorObserver {
  @override
  void didPush(
          _i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPush, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didPop(_i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPop, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didRemove(
          _i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didRemove, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didReplace(
          {_i16.Route<dynamic>? newRoute, _i16.Route<dynamic>? oldRoute}) =>
      super.noSuchMethod(
          Invocation.method(
              #didReplace, [], {#newRoute: newRoute, #oldRoute: oldRoute}),
          returnValueForMissingStub: null);
  @override
  void didStartUserGesture(
          _i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
          Invocation.method(#didStartUserGesture, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didStopUserGesture() =>
      super.noSuchMethod(Invocation.method(#didStopUserGesture, []),
          returnValueForMissingStub: null);
}
