// Mocks generated by Mockito 5.2.0 from annotations
// in internship_app_fis/test/login_page_widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;
import 'dart:typed_data' as _i14;

import 'package:file/file.dart' as _i4;
import 'package:flutter/widgets.dart' as _i15;
import 'package:flutter_cache_manager/flutter_cache_manager.dart' as _i5;
import 'package:flutter_cache_manager/src/cache_store.dart' as _i2;
import 'package:flutter_cache_manager/src/web/web_helper.dart' as _i3;
import 'package:internship_app_fis/models/internship.dart' as _i9;
import 'package:internship_app_fis/models/user.dart' as _i10;
import 'package:internship_app_fis/models/user_profile.dart' as _i12;
import 'package:internship_app_fis/services/internship_service.dart' as _i7;
import 'package:internship_app_fis/services/user_profile_service.dart' as _i11;
import 'package:internship_app_fis/services/user_service.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mysql1/mysql1.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCacheStore_0 extends _i1.Fake implements _i2.CacheStore {}

class _FakeWebHelper_1 extends _i1.Fake implements _i3.WebHelper {}

class _FakeFile_2 extends _i1.Fake implements _i4.File {}

class _FakeFileInfo_3 extends _i1.Fake implements _i5.FileInfo {}

class _FakeResults_4 extends _i1.Fake implements _i6.Results {}

/// A class which mocks [InternshipService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternshipService extends _i1.Mock implements _i7.InternshipService {
  MockInternshipService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> addInternship(_i9.Internship? internship) =>
      (super.noSuchMethod(Invocation.method(#addInternship, [internship]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<List<_i9.Internship>> getAllCompanyInternships(
          _i10.Company? company) =>
      (super.noSuchMethod(
              Invocation.method(#getAllCompanyInternships, [company]),
              returnValue:
                  Future<List<_i9.Internship>>.value(<_i9.Internship>[]))
          as _i8.Future<List<_i9.Internship>>);
  @override
  _i8.Future<List<_i9.Internship>> getAllInternships() => (super.noSuchMethod(
          Invocation.method(#getAllInternships, []),
          returnValue: Future<List<_i9.Internship>>.value(<_i9.Internship>[]))
      as _i8.Future<List<_i9.Internship>>);
  @override
  _i8.Future<List<_i9.Internship>> getStudentNotAppliedInternship(
          _i10.Student? user) =>
      (super.noSuchMethod(
              Invocation.method(#getStudentNotAppliedInternship, [user]),
              returnValue:
                  Future<List<_i9.Internship>>.value(<_i9.Internship>[]))
          as _i8.Future<List<_i9.Internship>>);
  @override
  _i8.Future<void> deleteInternship(_i9.Internship? internship) =>
      (super.noSuchMethod(Invocation.method(#deleteInternship, [internship]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<void> updateInternship(_i9.Internship? internship) =>
      (super.noSuchMethod(Invocation.method(#updateInternship, [internship]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i11.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i12.UserProfile?> getUserProfileById(_i10.User? user) =>
      (super.noSuchMethod(Invocation.method(#getUserProfileById, [user]),
              returnValue: Future<_i12.UserProfile?>.value())
          as _i8.Future<_i12.UserProfile?>);
  @override
  _i8.Future<void> addUserProfile(_i12.UserProfile? profile) =>
      (super.noSuchMethod(Invocation.method(#addUserProfile, [profile]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<List<_i12.CompanyProfile>> getAllCompanyProfiles() =>
      (super.noSuchMethod(Invocation.method(#getAllCompanyProfiles, []),
              returnValue: Future<List<_i12.CompanyProfile>>.value(
                  <_i12.CompanyProfile>[]))
          as _i8.Future<List<_i12.CompanyProfile>>);
  @override
  _i8.Future<List<_i12.StudentProfile>> getAcceptedParticipantsList(
          _i9.Internship? internship) =>
      (super.noSuchMethod(
              Invocation.method(#getAcceptedParticipantsList, [internship]),
              returnValue: Future<List<_i12.StudentProfile>>.value(
                  <_i12.StudentProfile>[]))
          as _i8.Future<List<_i12.StudentProfile>>);
  @override
  _i8.Future<List<_i12.StudentProfile>> getStudentProfilesByInternshipId(
          _i9.Internship? internship) =>
      (super.noSuchMethod(
          Invocation.method(#getStudentProfilesByInternshipId, [internship]),
          returnValue: Future<List<_i12.StudentProfile>>.value(
              <_i12.StudentProfile>[])) as _i8
          .Future<List<_i12.StudentProfile>>);
  @override
  _i8.Future<void> addAcceptedParticipantsList(
          _i9.Internship? internship, List<_i12.UserProfile>? userProfiles) =>
      (super.noSuchMethod(
          Invocation.method(
              #addAcceptedParticipantsList, [internship, userProfiles]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i13.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i10.User?> getUser(_i10.User? user) =>
      (super.noSuchMethod(Invocation.method(#getUser, [user]),
          returnValue: Future<_i10.User?>.value()) as _i8.Future<_i10.User?>);
  @override
  _i8.Future<bool> usernameExists(_i10.User? user) =>
      (super.noSuchMethod(Invocation.method(#usernameExists, [user]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<void> addUser(_i10.User? user) =>
      (super.noSuchMethod(Invocation.method(#addUser, [user]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<void> deleteUser(_i10.User? user) =>
      (super.noSuchMethod(Invocation.method(#deleteUser, [user]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
}

/// A class which mocks [DefaultCacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDefaultCacheManager extends _i1.Mock
    implements _i5.DefaultCacheManager {
  MockDefaultCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CacheStore get store => (super.noSuchMethod(Invocation.getter(#store),
      returnValue: _FakeCacheStore_0()) as _i2.CacheStore);
  @override
  _i3.WebHelper get webHelper =>
      (super.noSuchMethod(Invocation.getter(#webHelper),
          returnValue: _FakeWebHelper_1()) as _i3.WebHelper);
  @override
  _i8.Future<_i4.File> getSingleFile(String? url,
          {String? key, Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getSingleFile, [url], {#key: key, #headers: headers}),
              returnValue: Future<_i4.File>.value(_FakeFile_2()))
          as _i8.Future<_i4.File>);
  @override
  _i8.Stream<_i5.FileInfo> getFile(String? url,
          {String? key, Map<String, String>? headers}) =>
      (super.noSuchMethod(
          Invocation.method(#getFile, [url], {#key: key, #headers: headers}),
          returnValue:
              Stream<_i5.FileInfo>.empty()) as _i8.Stream<_i5.FileInfo>);
  @override
  _i8.Stream<_i5.FileResponse> getFileStream(String? url,
          {String? key,
          Map<String, String>? headers,
          bool? withProgress = false}) =>
      (super.noSuchMethod(
              Invocation.method(#getFileStream, [url],
                  {#key: key, #headers: headers, #withProgress: withProgress}),
              returnValue: Stream<_i5.FileResponse>.empty())
          as _i8.Stream<_i5.FileResponse>);
  @override
  _i8.Future<_i5.FileInfo> downloadFile(String? url,
          {String? key,
          Map<String, String>? authHeaders,
          bool? force = false}) =>
      (super.noSuchMethod(
              Invocation.method(#downloadFile, [url],
                  {#key: key, #authHeaders: authHeaders, #force: force}),
              returnValue: Future<_i5.FileInfo>.value(_FakeFileInfo_3()))
          as _i8.Future<_i5.FileInfo>);
  @override
  _i8.Future<_i5.FileInfo?> getFileFromCache(String? key,
          {bool? ignoreMemCache = false}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getFileFromCache, [key], {#ignoreMemCache: ignoreMemCache}),
              returnValue: Future<_i5.FileInfo?>.value())
          as _i8.Future<_i5.FileInfo?>);
  @override
  _i8.Future<_i5.FileInfo?> getFileFromMemory(String? key) =>
      (super.noSuchMethod(Invocation.method(#getFileFromMemory, [key]),
              returnValue: Future<_i5.FileInfo?>.value())
          as _i8.Future<_i5.FileInfo?>);
  @override
  _i8.Future<_i4.File> putFile(String? url, _i14.Uint8List? fileBytes,
          {String? key,
          String? eTag,
          Duration? maxAge = const Duration(days: 30),
          String? fileExtension = r'file'}) =>
      (super.noSuchMethod(
              Invocation.method(#putFile, [
                url,
                fileBytes
              ], {
                #key: key,
                #eTag: eTag,
                #maxAge: maxAge,
                #fileExtension: fileExtension
              }),
              returnValue: Future<_i4.File>.value(_FakeFile_2()))
          as _i8.Future<_i4.File>);
  @override
  _i8.Future<_i4.File> putFileStream(String? url, _i8.Stream<List<int>>? source,
          {String? key,
          String? eTag,
          Duration? maxAge = const Duration(days: 30),
          String? fileExtension = r'file'}) =>
      (super.noSuchMethod(
              Invocation.method(#putFileStream, [
                url,
                source
              ], {
                #key: key,
                #eTag: eTag,
                #maxAge: maxAge,
                #fileExtension: fileExtension
              }),
              returnValue: Future<_i4.File>.value(_FakeFile_2()))
          as _i8.Future<_i4.File>);
  @override
  _i8.Future<void> removeFile(String? key) =>
      (super.noSuchMethod(Invocation.method(#removeFile, [key]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<void> emptyCache() =>
      (super.noSuchMethod(Invocation.method(#emptyCache, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<void> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Stream<_i5.FileResponse> getImageFile(String? url,
          {String? key,
          Map<String, String>? headers,
          bool? withProgress = false,
          int? maxHeight,
          int? maxWidth}) =>
      (super.noSuchMethod(
              Invocation.method(#getImageFile, [
                url
              ], {
                #key: key,
                #headers: headers,
                #withProgress: withProgress,
                #maxHeight: maxHeight,
                #maxWidth: maxWidth
              }),
              returnValue: Stream<_i5.FileResponse>.empty())
          as _i8.Stream<_i5.FileResponse>);
}

/// A class which mocks [MySqlConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockMySqlConnection extends _i1.Mock implements _i6.MySqlConnection {
  MockMySqlConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<dynamic> close() =>
      (super.noSuchMethod(Invocation.method(#close, []),
          returnValue: Future<dynamic>.value()) as _i8.Future<dynamic>);
  @override
  _i8.Future<_i6.Results> query(String? sql, [List<Object?>? values]) =>
      (super.noSuchMethod(Invocation.method(#query, [sql, values]),
              returnValue: Future<_i6.Results>.value(_FakeResults_4()))
          as _i8.Future<_i6.Results>);
  @override
  _i8.Future<List<_i6.Results>> queryMulti(
          String? sql, Iterable<List<Object?>>? values) =>
      (super.noSuchMethod(Invocation.method(#queryMulti, [sql, values]),
              returnValue: Future<List<_i6.Results>>.value(<_i6.Results>[]))
          as _i8.Future<List<_i6.Results>>);
  @override
  _i8.Future<dynamic> transaction(Function? queryBlock) =>
      (super.noSuchMethod(Invocation.method(#transaction, [queryBlock]),
          returnValue: Future<dynamic>.value()) as _i8.Future<dynamic>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i15.NavigatorObserver {
  @override
  void didPush(
          _i15.Route<dynamic>? route, _i15.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPush, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didPop(_i15.Route<dynamic>? route, _i15.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPop, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didRemove(
          _i15.Route<dynamic>? route, _i15.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didRemove, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didReplace(
          {_i15.Route<dynamic>? newRoute, _i15.Route<dynamic>? oldRoute}) =>
      super.noSuchMethod(
          Invocation.method(
              #didReplace, [], {#newRoute: newRoute, #oldRoute: oldRoute}),
          returnValueForMissingStub: null);
  @override
  void didStartUserGesture(
          _i15.Route<dynamic>? route, _i15.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
          Invocation.method(#didStartUserGesture, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didStopUserGesture() =>
      super.noSuchMethod(Invocation.method(#didStopUserGesture, []),
          returnValueForMissingStub: null);
}
